/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.components;



import DTO.Tour;
import java.awt.Color;
import java.awt.Font;

import java.awt.Image;
import java.awt.MediaTracker;
import java.util.Locale;
import GUI.App;



import javax.swing.ImageIcon;

import javax.swing.SwingUtilities;

/**
 *
 * @author ACER
 */
public class CartItem extends javax.swing.JPanel {

    /**
     * Creates new form CartItem
     */

   
    private String  cartId;
    private Tour tour;
    public CartItem() {
        initComponents();
     
      
    }
    public String formatPrice(Double price) {
    java.text.NumberFormat formatter = java.text.NumberFormat.getCurrencyInstance(new Locale("vi", "VN"));
    String formattedPrice = formatter.format(price*1000);
  
    formattedPrice = formattedPrice.replace("₫", "").trim() + " ₫";
    return formattedPrice;
}
    public void setInfo(Tour tour){
        jLabel2.setText( "Tên Tour:"+tour.getTitle());
        jLabel1.setText(formatPrice(tour.getPrice_one_person()));
         jLabel1.setForeground(Color.red);
     jLabel1.setFont(new Font("Serif", Font.BOLD, 14));
       jLabel5.setText("<html>"+"Địa chỉ:"+tour.getAddress()+"</html>");
        setDesciption("<html>"+"Mô tả:"+tour.getDestination_description()+"</html>");
        setImage(App.globalPathApp+  "\\Store_img\\"+tour.getImgUrl());
        setDateStart("Thời gian bắt đầu:"+tour.getTime_book_start().toString());
        setDateEnd("Thời gian kết thúc:"+tour.getTime_book_end().toString());
        setQuantity(tour.getQuantity());
    }
    public void setTour(Tour tour) {
      this.tour = tour;
    }
    
    public Tour getTour() {
     return this.tour;
    }
    public void setCartIid(String id) {
     this.cartId  =id;
    }
    public String getCartId () {
     return this.cartId;
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // ===================== function resize img=======================
   
       private Image resizeImg(String filePath) {
        ImageIcon icon = new ImageIcon(filePath);
        if (icon.getImageLoadStatus() != MediaTracker.COMPLETE) {
            throw new IllegalArgumentException("Failed to load image from path: " + filePath);
        }
        return icon.getImage().getScaledInstance(170, 170, Image.SCALE_SMOOTH);
    }
    public void setImage(String filePath) {
         
       if (filePath == null || filePath.isEmpty()) {
           
        }
        Image img = resizeImg(filePath);
        ImageIcon icon = new ImageIcon(img);
        // Ensuring the UI update is done on the Event Dispatch Thread
        SwingUtilities.invokeLater(() -> buttonRadius1.setIcon(icon));
    
    }
    public void setNameTour(String name) {
      jLabel2.setText(name);
    }
    public String getName() {
     return   this.jLabel2.getText();
    }
    public void setAddress(String Address){
     jLabel5.setText(Address);
    }
    public void setPrice(String price) {
     jLabel1.setText(price);
     jLabel1.setForeground(Color.red);
     jLabel1.setFont(new Font("Serif", Font.BOLD, 14));
    }
    public void setDesciption(String t) {
         jLabel4.setText(t);
    }
    public void setDateStart(String t) {
       dateStart.setText(t);
    }
    public void setDateEnd(String t) {
      dateEnd.setText(t);
    }
    public  void setQuantity(int i) {
        quantity.setText("số chổ :"+i);
    }
    public  ButtonRadius getButtonDelete() {
     return this.buttonDelete;
    }
     public  ButtonRadius getButtonEdit() {
     return this.buttonEdit;
    }
     public ButtonRadius getButtonOrder() {
      return this.buttonOrder;
     }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonRadius1 = new GUI.components.ButtonRadius();
        panelRadius1 = new GUI.components.PanelRadius();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dateEnd = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dateStart = new javax.swing.JLabel();
        panelRadius3 = new GUI.components.PanelRadius();
        buttonDelete = new GUI.components.ButtonRadius();
        buttonEdit = new GUI.components.ButtonRadius();
        buttonOrder = new GUI.components.ButtonRadius();
        quantity = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonRadius1.setText("no image");
        buttonRadius1.setBorderColor(new java.awt.Color(0, 0, 0));
        buttonRadius1.setRadius(20);
        add(buttonRadius1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, 170));

        panelRadius1.setBackground(new java.awt.Color(255, 255, 255));
        panelRadius1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText(" price");
        panelRadius1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 150, 30));

        jLabel2.setText("name: không có thông tin");
        panelRadius1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 4, 170, 40));

        dateEnd.setText("Ngày kết thúc:không có thông tin");
        panelRadius1.add(dateEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 180, 20));

        jLabel4.setText("mô tảkhông có thông tin");
        panelRadius1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 180, 50));

        jLabel5.setText(" Address:không có thông tin");
        panelRadius1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 180, 40));

        dateStart.setText("Ngày bắt đầu:không có thông tin");
        panelRadius1.add(dateStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 180, 20));

        add(panelRadius1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 200, 230));

        panelRadius3.setBackground(new java.awt.Color(255, 255, 255));
        panelRadius3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonDelete.setBackground(new java.awt.Color(255, 0, 51));
        buttonDelete.setForeground(new java.awt.Color(255, 255, 255));
        buttonDelete.setText("Delete");
        buttonDelete.setBorderColor(new java.awt.Color(255, 0, 0));
        buttonDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonDelete.setRadius(10);
        panelRadius3.add(buttonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 90, 30));

        buttonEdit.setBackground(new java.awt.Color(0, 51, 204));
        buttonEdit.setForeground(new java.awt.Color(255, 255, 255));
        buttonEdit.setText("Edit");
        buttonEdit.setBorderColor(new java.awt.Color(0, 51, 204));
        buttonEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonEdit.setRadius(10);
        panelRadius3.add(buttonEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 90, 30));

        buttonOrder.setBackground(new java.awt.Color(133, 108, 189));
        buttonOrder.setForeground(new java.awt.Color(255, 255, 255));
        buttonOrder.setText("Đặt Tour");
        buttonOrder.setBorderColor(new java.awt.Color(255, 255, 255));
        buttonOrder.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonOrder.setRadius(20);
        panelRadius3.add(buttonOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 140, 30));

        quantity.setText(" số chổ   còn lại:");
        panelRadius3.add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 150, 30));

        add(panelRadius3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 310));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.components.ButtonRadius buttonDelete;
    private GUI.components.ButtonRadius buttonEdit;
    private GUI.components.ButtonRadius buttonOrder;
    private GUI.components.ButtonRadius buttonRadius1;
    private javax.swing.JLabel dateEnd;
    private javax.swing.JLabel dateStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private GUI.components.PanelRadius panelRadius1;
    private GUI.components.PanelRadius panelRadius3;
    private javax.swing.JLabel quantity;
    // End of variables declaration//GEN-END:variables

  

   
   
    
}
