/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.components;

/**
 *
 * @author ACER
 */
public class TabeButtonAction extends javax.swing.JPanel {

    /**
     * Creates new form TabeButtonAction
     */
    public TabeButtonAction() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonRadius1 = new GUI.components.ButtonRadius();
        buttonRadius2 = new GUI.components.ButtonRadius();
        buttonRadius3 = new GUI.components.ButtonRadius();

        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(118, 45));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonRadius1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon-delete.png"))); // NOI18N
        buttonRadius1.setText("Xóa");
        buttonRadius1.setBorderColor(new java.awt.Color(255, 0, 51));
        buttonRadius1.setColorOver(new java.awt.Color(255, 102, 102));
        buttonRadius1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonRadius1.setIconTextGap(8);
        buttonRadius1.setRadius(8);
        add(buttonRadius1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 150, 40));

        buttonRadius2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon-add.png"))); // NOI18N
        buttonRadius2.setText("Thêm");
        buttonRadius2.setBorderColor(new java.awt.Color(0, 0, 204));
        buttonRadius2.setColorClick(new java.awt.Color(255, 255, 255));
        buttonRadius2.setColorOver(new java.awt.Color(102, 102, 255));
        buttonRadius2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonRadius2.setIconTextGap(8);
        buttonRadius2.setRadius(8);
        add(buttonRadius2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, 40));

        buttonRadius3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon-edit.png"))); // NOI18N
        buttonRadius3.setText("Sửa");
        buttonRadius3.setBorderColor(new java.awt.Color(0, 204, 51));
        buttonRadius3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonRadius3.setIconTextGap(8);
        buttonRadius3.setRadius(8);
        add(buttonRadius3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 150, 40));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.components.ButtonRadius buttonRadius1;
    private GUI.components.ButtonRadius buttonRadius2;
    private GUI.components.ButtonRadius buttonRadius3;
    // End of variables declaration//GEN-END:variables
}
