/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.panel;

/**
 *
 * @author ACER
 */
public class NguoiDung extends javax.swing.JPanel {

    /**
     * Creates new form NguoiDung
     */
    public NguoiDung() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRadius1 = new GUI.components.PanelRadius();
        jLabel1 = new javax.swing.JLabel();
        panelRadius2 = new GUI.components.PanelRadius();
        jTextField2 = new javax.swing.JTextField();
        buttonRadius1 = new GUI.components.ButtonRadius();
        panelRadius3 = new GUI.components.PanelRadius();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRadius1.setForeground(new java.awt.Color(255, 255, 255));
        panelRadius1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Thông kê người dùng");
        panelRadius1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        panelRadius2.setBackground(new java.awt.Color(255, 255, 255));
        panelRadius2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.setFont(new java.awt.Font("JetBrains Mono NL Medium", 0, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        jTextField2.setBorder(null);
        panelRadius2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 2, 360, 30));

        buttonRadius1.setText("Tìm Kiếm");
        buttonRadius1.setBorderColor(new java.awt.Color(0, 0, 0));
        buttonRadius1.setRadius(10);
        panelRadius2.add(buttonRadius1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 110, 40));

        panelRadius1.add(panelRadius2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 5, 490, 40));

        add(panelRadius1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 20, 970, 50));
        add(panelRadius3, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 80, 970, 50));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 960, 490));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.components.ButtonRadius buttonRadius1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private GUI.components.PanelRadius panelRadius1;
    private GUI.components.PanelRadius panelRadius2;
    private GUI.components.PanelRadius panelRadius3;
    // End of variables declaration//GEN-END:variables
}
