/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.panel;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class TourDuLich extends javax.swing.JPanel {

    /**
     * Creates new form TourDuLich
     */
    public TourDuLich() {
        initComponents();
        addValueTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void addValueTable(){
        DefaultTableModel model  = (DefaultTableModel)  this.jTable1.getModel();
        String data[] ={"1","2","3","4","5"};
        model.addRow(data);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRadius1 = new GUI.components.PanelRadius();
        jLabel1 = new javax.swing.JLabel();
        panelRadius2 = new GUI.components.PanelRadius();
        jTextField2 = new javax.swing.JTextField();
        buttonRadius1 = new GUI.components.ButtonRadius();
        panelRadius3 = new GUI.components.PanelRadius();
        tabeButtonAction2 = new GUI.components.TabeButtonAction();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRadius1.setForeground(new java.awt.Color(255, 255, 255));
        panelRadius1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Thống Kê Tour du lịch");
        panelRadius1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        panelRadius2.setBackground(new java.awt.Color(255, 255, 255));
        panelRadius2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.setFont(new java.awt.Font("JetBrains Mono NL Medium", 0, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        jTextField2.setBorder(null);
        panelRadius2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 2, 360, 30));

        buttonRadius1.setText("Tìm Kiếm");
        buttonRadius1.setBorderColor(new java.awt.Color(0, 0, 0));
        buttonRadius1.setRadius(10);
        panelRadius2.add(buttonRadius1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 110, 40));

        panelRadius1.add(panelRadius2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 5, 490, 40));

        add(panelRadius1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 940, 50));

        panelRadius3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelRadius3.add(tabeButtonAction2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 510, -1));

        add(panelRadius3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 940, 50));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "", "hình  ảnh", "Tên", "địa chỉ", "Giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 930, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.components.ButtonRadius buttonRadius1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private GUI.components.PanelRadius panelRadius1;
    private GUI.components.PanelRadius panelRadius2;
    private GUI.components.PanelRadius panelRadius3;
    private GUI.components.TabeButtonAction tabeButtonAction2;
    // End of variables declaration//GEN-END:variables
}
